surfin:
  system:
    timezone: Asia/Tokyo
    logging: # Set log level to DEBUG
      level: DEBUG
  batch:
    job_name: helloWorldJob
    polling_interval_seconds: 5
    chunk_size: 1000
    item_retry:
      max_attempts: 3
      initial_interval: 100
      retryable_exceptions: # Retryable exceptions for item processing
        - "BatchError"
    item_skip:
      skip_limit: 10
      skippable_exceptions: # Skippable exceptions for item processing
        - "BatchError" # No need for datasources and infrastructure sections for in-memory DB
    job_repository_db_ref: dummy
  database: # Renamed from adapter_configs to database
    metadata: # Dummy configuration for 'metadata' database, referenced by framework migrations
      type: dummy
      host: "" # Dummy value
      port: 0 # Dummy value
      database: "" # Dummy value
      user: "" # Dummy value
      password: "" # Dummy value
      sslmode: "" # Dummy value
    dummy: # Dummy configuration for 'dummy' database, which should skip migrations
      type: dummy
      host: "" # Dummy value
      port: 0 # Dummy value
      database: "" # Dummy value
      user: "" # Dummy value
      password: "" # Dummy value
      sslmode: "" # Dummy value
  security:
    masked_parameter_keys:
      - "password"
      - "api_key"
